// Planes
#define TURF_PLANE -60
#define WORLD_PLANE -50
#define LIGHTING_PLANE -40
#define BLACKNESS_PLANE 0
#define UI_PLANE 10

// Layers
#define LIGHTING_LAYER 100
#define UI_LAYER 200

// Equippable layers
#define HEAD_LAYER FLOAT_LAYER - 0.1
#define BELT_LAYER FLOAT_LAYER - 0.2
#define ARMOR_LAYER FLOAT_LAYER - 0.3
#define	CLOTHING_LAYER FLOAT_LAYER - 0.4
#define LEGS_LAYER FLOAT_LAYER - 0.5